
version: '3'
services:
  keduroam-radius:
    restart: always
    container_name: keduroam-radius
    image: chrisryu/keduroam-radius:latest
    ports:
    - 1812-1813:1812-1813/udp
    - 80:80
    env_file: 
    - ./envs/keduroam.env
    - ./envs/global.env
    volumes:
    - mysql_data:/var/lib/mysql
    - /:/rootfs:ro
    depends_on:
    - keduroam-rest

  keduroam-rest:
    restart: always
    container_name: keduroam-rest
    image: chrisryu/keduroam-rest:oracle9i
    env_file: 
    - ./envs/global.env
    env_file:
    - ./envs/db_server_oracle.env

  keduroam-dashboard:
    image: chrisryu/keduroam-dashboard:latest
    container_name: keduroam-dashboard
    ports:
      - '8080:80'

    volumes:
      - ./dashboard_state/data/whisper:/opt/graphite/storage/whisper
      - ./dashboard_state/data/grafana:/opt/grafana/data
      - ./dashboard_state/log/graphite:/opt/graphite/storage/log
      - ./dashboard_state/log/supervisor:/var/log/supervisor

volumes:       
  mysql_data:
    external: true
